### ISSUE TITLE
[Bug] Integration test is broken

### ISSUE THREAD

**Issue by vicsn** [AleoHQ/snarkOS#3554]
## 🐛 Bug Report

The following test is broken:

```
integration:
    docker:
      - image: cimg/rust:1.83.0 # Attention - Change the MSRV in Cargo.toml and rust-toolchain as well
    resource_class: << pipeline.parameters.medium >>
    steps:
      - run_serial_long:
          workspace_member: .integration
          cache_key: v3.3.1-rust-1.83.0-integration-cache
```

```
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0,12 * * *"
          filters:
            branches:
              only:
                - mainnet
    jobs:
      - integration
```

It tries to sync. The code in the `.integration` folder is outdated and I'm getting a spammy failure message about this multiple times per day. 

I suggest we **remove** the `.integration` folder and the above job for now. Instead, we should make syncing part of the monthly release process - assuring we have a proper feedback loop between the test result and the next release.
