### ISSUE TITLE
[Feature] Add Clippy to Github Actions

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#514]
## 🚀 Feature

Add the following Clippy check to Github Actions

## Implementation

```
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    strategy:
      matrix:
        rust:
          - stable
          - nightly

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy

      - name: Check examples
        uses: actions-rs/cargo@v1
        with:
            command: clippy
            args: --examples --all

      - name: Check examples with all features on stable
        uses: actions-rs/cargo@v1
        with:
            command: clippy
            args: --examples --all-features --all
        if: matrix.rust == 'stable'

      - name: Check benchmarks on nightly
        uses: actions-rs/cargo@v1
        with:
            command: clippy
            args: --all-features --examples --all --benches
        if: matrix.rust == 'nightly'
```

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Yes
